name: "stroopwafelshop"
version: "1.0.0"
config-version: 2

profile: "stroopwafelshop"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  stroopwafelshop:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
      +schema: stg
    marts:
      +materialized: table
      +schema: mart
