stroopwafelshop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: mdp
      password: mdp_password
      port: 5432
      dbname: warehouse
      schema: analytics
      threads: 4
